---
phantomjs_distro: '{{ ansible_system | lower }}'
phantomjs_arch: '{{ ansible_userspace_architecture }}'
phantomjs_src: 'phantomjs-{{ phantomjs_version }}-{{ phantomjs_distro }}-{{ phantomjs_arch }}.tar.bz2'
phantomjs_dir: '{{ project_user_home }}/.phantomjs/{{ phantomjs_version }}/{{ phantomjs_arch }}-{{ phantomjs_distro }}'
