---
- block:
  - name: create phantomjs dir
    file:
      path: '{{ phantomjs_dir }}'
      state: directory

  - name: copy cached phantomjs
    copy:
      src: '{{ local_files_dir }}/{{ phantomjs_src }}'
      dest: /tmp/{{ phantomjs_src }}
    register: cached_pjs
    ignore_errors: True

  - name: download phantomjs
    get_url:
      url: https://bitbucket.org/ariya/phantomjs/downloads/{{ phantomjs_src }}
      dest: /tmp/{{ phantomjs_src }}
    when: cached_pjs is failed

  - name: unarchive phantomjs
    unarchive:
      extra_opts: ['--strip-components=1', '--show-stored-names']
      remote_src: yes
      src: /tmp/{{ phantomjs_src }}
      dest: '{{ phantomjs_dir }}'
      creates: '{{ phantomjs_dir }}/bin/phantomjs'
  become: yes
  become_user: '{{ project_owner }}'

- name: cache phantomjs for the future
  fetch:
    src: /tmp/{{ phantomjs_src }}
    dest: '{{ local_files_dir }}/'
    flat: True
  when:
    - cached_pjs is failed
    - ansible_virtualization_type == 'virtualbox'
