---
- name: get os-specific settings
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}-{{ansible_distribution_version }}.yml"
        - "{{ ansible_distribution|lower }}-{{ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - "{{ role_path }}/vars"

- name: update all packages to the latest version
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
    update_cache: yes
    cache_valid_time: '{{ apt_cache_timeout }}'
  when: perform_dist_upgrade|bool

- name: install building software and build essentials
  apt:
    name: '{{ common_essential_packages }}'
    state: present
    cache_valid_time: '{{ apt_cache_timeout }}'
    update_cache: yes

- name: update python's crypto libs
  pip:
    name: ['urllib3', 'pyopenssl', 'ndg-httpsclient', 'pyasn1']
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '14'
