---
passenger_instances: 2
nginx_max_upload_size: "{{ project_max_upload_size|default('200m') }}"
project_git_url: https://github.com/VTUL/{{ project_name }}.git
project_deploy_key: ''
project_app_root: '{{ project_owner_home }}/{{ project_name }}'
project_noid_statefile: '/var/sufia/minter-state'
# Name of Solr test core used by application
project_solr_test_core: 'test'
# ORCID API endpoints
project_orcid_site_url: "{{ 'http://api.orcid.org' if project_orcid_service == 'production' else 'http://api.sandbox.orcid.org' }}"
project_orcid_token_url: "{{ 'https://api.orcid.org/oauth/token' if project_orcid_service == 'production' else 'https://api.sandbox.orcid.org/oauth/token' }}"
project_orcid_remote_signin_url: "{{ 'https://orcid.org/signin/auth.json' if project_orcid_service == 'production' else 'https://sandbox.orcid.org/signin/auth.json' }}"
project_orcid_authorize_url: "{{ 'https://orcid.org/oauth/authorize' if project_orcid_service == 'production' else 'https://sandbox.orcid.org/oauth/authorize' }}"
# Graylog production logging defaults
graylog_enable: "{{ 'true' if project_app_env == 'production' else 'false' }}"
graylog_host: 127.0.0.1
graylog_port: 12201
graylog_protocol: udp
graylog_network_locality: WAN
graylog_facility: "{{ project_name }}"
graylog_verbosity: "info"
# OSF API settings
osf_client_id: ""
osf_client_secret: ""
# Google Analytics
sufia_google_analytics_comment_marker: "{{ '' if project_google_analytics_id is defined else '#' }}"

