---
- name: install fits installation dependencies
  apt:
    name: ['unzip']
    state: present
    cache_valid_time: '{{ apt_cache_timeout }}'
    update_cache: yes

- name: copy cached fits
  copy:
    src: '{{ local_files_dir }}/fits-{{ fits_version }}.zip'
    dest: /tmp/fits-{{ fits_version }}.zip
  register: cached_fits
  ignore_errors: True

- name: download fits distribution to /tmp
  get_url:
    url: "{{ fits_download_url }}/fits-{{ fits_version }}.zip"
    dest: /tmp/fits-{{ fits_version }}.zip
    owner: root
    group: root
    mode: 0444
    timeout: 100
  when: cached_fits is failed

- name: cache fits for the future
  fetch:
    src: /tmp/fits-{{ fits_version }}.zip
    dest: '{{ local_files_dir }}/'
    flat: True
  when:
    - cached_fits is failed
    - ansible_virtualization_type == 'virtualbox'

- name: unarchive fits distribution
  unarchive:
    src: /tmp/fits-{{ fits_version }}.zip
    dest: /opt
    copy: no
    creates: /opt/fits-{{ fits_version }}/fits.sh

- name: ensure fits directory is accessible
  file:
    path: /opt/fits-{{ fits_version }}
    mode: a+x

- name: link desired version of fits to /opt/fits
  file:
    src: /opt/fits-{{ fits_version }}
    dest: /opt/fits
    state: link

- name: ensure fits.sh is executable
  file:
    path: /opt/fits-{{ fits_version }}/fits.sh
    mode: a+x
